# Generated by Django 5.2.17 on 2026-09-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_create_groups'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='one_current_term'),
        ),
    ]
